"""Seed data for the exercises reference table.

Run this module to populate the exercises table with common gym exercises.
Usage: python -m app.seed_exercises
"""

from __future__ import annotations

EXERCISES = [
    # Chest
    {
        "name": "Panca piana con bilanciere",
        "name_en": "Barbell Bench Press",
        "muscle_groups": ["chest", "triceps", "shoulders"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "Distensioni su panca piana con bilanciere",
        "description_en": "Flat bench press with barbell",
    },
    {
        "name": "Panca inclinata con manubri",
        "name_en": "Incline Dumbbell Press",
        "muscle_groups": ["chest", "shoulders", "triceps"],
        "equipment": "dumbbell",
        "exercise_type": "weighted",
        "description": "Distensioni su panca inclinata con manubri",
        "description_en": "Incline bench press with dumbbells",
    },
    {
        "name": "Croci ai cavi",
        "name_en": "Cable Flyes",
        "muscle_groups": ["chest"],
        "equipment": "cable",
        "exercise_type": "weighted",
        "description": "Croci ai cavi alti o bassi",
        "description_en": "Cable flye crossovers",
    },
    {
        "name": "Piegamenti sulle braccia",
        "name_en": "Push-ups",
        "muscle_groups": ["chest", "triceps", "shoulders"],
        "equipment": None,
        "exercise_type": "bodyweight",
        "description": "Piegamenti a terra",
        "description_en": "Standard push-ups",
    },
    {
        "name": "Chest press alla macchina",
        "name_en": "Machine Chest Press",
        "muscle_groups": ["chest", "triceps"],
        "equipment": "machine",
        "exercise_type": "weighted",
        "description": "Distensioni alla macchina chest press",
        "description_en": "Machine chest press",
    },
    # Back
    {
        "name": "Trazioni alla sbarra",
        "name_en": "Pull-ups",
        "muscle_groups": ["back", "biceps"],
        "equipment": "bodyweight",
        "exercise_type": "bodyweight",
        "description": "Trazioni alla sbarra a presa prona",
        "description_en": "Overhand grip pull-ups",
    },
    {
        "name": "Rematore con bilanciere",
        "name_en": "Barbell Row",
        "muscle_groups": ["back", "biceps"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "Rematore con bilanciere a busto flesso",
        "description_en": "Bent-over barbell row",
    },
    {
        "name": "Lat machine",
        "name_en": "Lat Pulldown",
        "muscle_groups": ["back", "biceps"],
        "equipment": "cable",
        "exercise_type": "weighted",
        "description": "Lat pulldown avanti al petto",
        "description_en": "Front lat pulldown",
    },
    {
        "name": "Pulley basso",
        "name_en": "Seated Cable Row",
        "muscle_groups": ["back", "biceps"],
        "equipment": "cable",
        "exercise_type": "weighted",
        "description": "Rematore al cavo basso da seduto",
        "description_en": "Seated cable row",
    },
    {
        "name": "Stacco da terra",
        "name_en": "Deadlift",
        "muscle_groups": ["back", "legs", "glutes"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "Stacco da terra convenzionale",
        "description_en": "Conventional deadlift",
    },
    # Shoulders
    {
        "name": "Military press con bilanciere",
        "name_en": "Overhead Press",
        "muscle_groups": ["shoulders", "triceps"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "Pressa sopra la testa con bilanciere",
        "description_en": "Standing barbell overhead press",
    },
    {
        "name": "Alzate laterali con manubri",
        "name_en": "Lateral Raises",
        "muscle_groups": ["shoulders"],
        "equipment": "dumbbell",
        "exercise_type": "weighted",
        "description": "Alzate laterali con manubri",
        "description_en": "Dumbbell lateral raises",
    },
    {
        "name": "Alzate frontali",
        "name_en": "Front Raises",
        "muscle_groups": ["shoulders"],
        "equipment": "dumbbell",
        "exercise_type": "weighted",
        "description": "Alzate frontali con manubri",
        "description_en": "Dumbbell front raises",
    },
    {
        "name": "Face pull ai cavi",
        "name_en": "Face Pulls",
        "muscle_groups": ["shoulders", "back"],
        "equipment": "cable",
        "exercise_type": "weighted",
        "description": "Face pull ai cavi con corda",
        "description_en": "Cable face pulls with rope",
    },
    # Legs
    {
        "name": "Squat con bilanciere",
        "name_en": "Barbell Squat",
        "muscle_groups": ["legs", "glutes"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "Squat con bilanciere alto",
        "description_en": "High bar barbell squat",
    },
    {
        "name": "Leg press",
        "name_en": "Leg Press",
        "muscle_groups": ["legs", "glutes"],
        "equipment": "machine",
        "exercise_type": "weighted",
        "description": "Pressa per le gambe a 45 gradi",
        "description_en": "45-degree leg press",
    },
    {
        "name": "Leg extension",
        "name_en": "Leg Extension",
        "muscle_groups": ["legs"],
        "equipment": "machine",
        "exercise_type": "weighted",
        "description": "Estensione delle gambe alla macchina",
        "description_en": "Machine leg extension",
    },
    {
        "name": "Leg curl",
        "name_en": "Leg Curl",
        "muscle_groups": ["legs"],
        "equipment": "machine",
        "exercise_type": "weighted",
        "description": "Curl per le gambe alla macchina",
        "description_en": "Machine leg curl",
    },
    {
        "name": "Affondi con manubri",
        "name_en": "Dumbbell Lunges",
        "muscle_groups": ["legs", "glutes"],
        "equipment": "dumbbell",
        "exercise_type": "weighted",
        "description": "Affondi in avanzamento con manubri",
        "description_en": "Walking dumbbell lunges",
    },
    {
        "name": "Calf raises alla macchina",
        "name_en": "Machine Calf Raises",
        "muscle_groups": ["calves"],
        "equipment": "machine",
        "exercise_type": "weighted",
        "description": "Sollevamenti sui polpacci alla macchina",
        "description_en": "Standing machine calf raises",
    },
    # Arms
    {
        "name": "Curl con bilanciere",
        "name_en": "Barbell Curl",
        "muscle_groups": ["biceps"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "Curl per i bicipiti con bilanciere",
        "description_en": "Standing barbell curl",
    },
    {
        "name": "Curl con manubri",
        "name_en": "Dumbbell Curl",
        "muscle_groups": ["biceps"],
        "equipment": "dumbbell",
        "exercise_type": "weighted",
        "description": "Curl alternato con manubri",
        "description_en": "Alternating dumbbell curl",
    },
    {
        "name": "Pushdown ai cavi",
        "name_en": "Cable Pushdown",
        "muscle_groups": ["triceps"],
        "equipment": "cable",
        "exercise_type": "weighted",
        "description": "Pushdown ai cavi per i tricipiti",
        "description_en": "Cable tricep pushdown",
    },
    {
        "name": "French press con bilanciere",
        "name_en": "Skull Crushers",
        "muscle_groups": ["triceps"],
        "equipment": "barbell",
        "exercise_type": "weighted",
        "description": "French press con bilanciere EZ",
        "description_en": "EZ bar skull crushers",
    },
    {
        "name": "Dip alle parallele",
        "name_en": "Parallel Bar Dips",
        "muscle_groups": ["triceps", "chest", "shoulders"],
        "equipment": "bodyweight",
        "exercise_type": "bodyweight",
        "description": "Dip alle parallele",
        "description_en": "Parallel bar dips",
    },
    # Core
    {
        "name": "Crunch",
        "name_en": "Crunch",
        "muscle_groups": ["abs"],
        "equipment": None,
        "exercise_type": "bodyweight",
        "description": "Crunch classico a terra",
        "description_en": "Standard floor crunch",
    },
    {
        "name": "Plank",
        "name_en": "Plank",
        "muscle_groups": ["abs", "core"],
        "equipment": None,
        "exercise_type": "timed",
        "description": "Plank frontale in isometria",
        "description_en": "Front plank hold",
    },
    {
        "name": "Russian twist",
        "name_en": "Russian Twist",
        "muscle_groups": ["abs", "obliques"],
        "equipment": None,
        "exercise_type": "weighted",
        "description": "Russian twist con peso",
        "description_en": "Weighted Russian twist",
    },
    {
        "name": "Leg raise alla sbarra",
        "name_en": "Hanging Leg Raises",
        "muscle_groups": ["abs"],
        "equipment": "bodyweight",
        "exercise_type": "bodyweight",
        "description": "Sollevamento gambe alla sbarra",
        "description_en": "Hanging leg raises",
    },
    # Cardio
    {
        "name": "Corsa su treadmill",
        "name_en": "Treadmill Running",
        "muscle_groups": ["cardio", "legs"],
        "equipment": "treadmill",
        "exercise_type": "timed",
        "description": "Corsa sul tapis roulant",
        "description_en": "Treadmill running",
    },
    {
        "name": "Cyclette",
        "name_en": "Stationary Bike",
        "muscle_groups": ["cardio", "legs"],
        "equipment": "bike",
        "exercise_type": "timed",
        "description": "Cyclette stazionaria",
        "description_en": "Stationary bike cycling",
    },
    {
        "name": "Vogatore",
        "name_en": "Rowing Machine",
        "muscle_groups": ["cardio", "back", "legs"],
        "equipment": "rowing_machine",
        "exercise_type": "timed",
        "description": "Vogatore (rowing machine)",
        "description_en": "Rowing machine",
    },
]
